### ISSUE TITLE
Is this still stable....

### ISSUE THREAD

**Issue by Jpac14** [Jestemkioskiem/Fivem-api#1]
Is this stable in a production environment?

**Comment by RedstonedLife** [comment]
Should be, If you can do `http://ip:port/info.json` (`http://endpoint/info.json`)
Or `/players.json` then yes, It is. I'm using this right now.

Only thing different, Is the json structure.
So just use the domain, learn the json keys, then build your framework around it.

**Comment by wmetryka** [comment]
I haven't used it in a while but I've checked against current API documentation and it seems like this should indeed still work.
